export const portfolioProjects = [
  {
    slug: "microfinance-ops-suite",
    title: "Microfinance Operations Suite",
    client: "Confidential Finance Client (NDA)",
    industry: "Financial Services",
    serviceTrack: "Web App Development",
    category: "Web App",
    summary:
      "A branch-ready loan operations system with real-time repayment tracking, role-based access, and daily reporting automation.",
    challenge:
      "The team handled loan records through manual sheets, causing delayed reconciliation and weak branch-level visibility.",
    strategy: [
      "Mapped head-office and branch workflows into one data model",
      "Built role-aware dashboard for operations, audit, and leadership",
      "Automated repayment logging and daily summary generation",
    ],
    deliverables: ["Product architecture", "UI/UX system", "Admin analytics", "Release and handover"],
    outcomes: ["52% faster reconciliation", "34% reduction in entry errors", "3.4x faster report turnaround"],
    stack: ["Next.js", "Node.js", "PostgreSQL", "Charting"],
    duration: "10 weeks",
    year: "2025",
    teamSize: "6 specialists",
    accent: "from-cyan-400 to-blue-500",
    coverImage: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=1400&auto=format&fit=crop",
    challengeImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1200&auto=format&fit=crop",
    strategyImage: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=1200&auto=format&fit=crop",
    outcomeImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "meta-performance-engine",
    title: "Meta Performance Engine",
    client: "Regional Wellness Brand",
    industry: "Health and Fitness",
    serviceTrack: "Data Driven Meta Ads Campaign",
    category: "Marketing",
    summary:
      "A performance campaign framework with conversion events, creative testing matrix, and weekly scaling decisions.",
    challenge:
      "Ad budget increased month-over-month but cost per qualified lead remained unstable due to fragmented tracking.",
    strategy: [
      "Implemented event architecture with Pixel and CAPI",
      "Designed audience ladder from cold to high-intent pools",
      "Created creative rotation rhythm based on fatigue signals",
    ],
    deliverables: ["Campaign build", "Creative testing framework", "Attribution dashboard", "Optimization SOP"],
    outcomes: ["2.9x ROAS in 45 days", "41% lower CPL", "18% increase in qualified appointments"],
    stack: ["Meta Ads", "GA4", "Looker Studio", "UTM Governance"],
    duration: "6 weeks",
    year: "2025",
    teamSize: "4 specialists",
    accent: "from-orange-400 to-amber-500",
    coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1400&auto=format&fit=crop",
    challengeImage: "https://images.unsplash.com/photo-1552581234-26160f608093?q=80&w=1200&auto=format&fit=crop",
    strategyImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1200&auto=format&fit=crop",
    outcomeImage: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "premium-brand-refresh",
    title: "Premium Brand Refresh",
    client: "Interior and Lifestyle Company",
    industry: "Retail and Design",
    serviceTrack: "Branding",
    category: "Branding",
    summary:
      "A full identity refresh across logo system, visual language, and brand communication for higher-ticket positioning.",
    challenge:
      "The brand looked inconsistent across channels and did not communicate premium value clearly.",
    strategy: [
      "Defined positioning and narrative pillars",
      "Built a coherent visual system and type hierarchy",
      "Standardized brand behavior across digital touchpoints",
    ],
    deliverables: ["Brand strategy", "Identity kit", "Guideline document", "Marketing templates"],
    outcomes: ["63% growth in qualified inquiries", "Higher premium plan conversion", "Consistent brand usage across channels"],
    stack: ["Figma", "Adobe Illustrator", "Design QA"],
    duration: "4 weeks",
    year: "2025",
    teamSize: "3 specialists",
    accent: "from-rose-400 to-red-500",
    coverImage: "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?q=80&w=1400&auto=format&fit=crop",
    challengeImage: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?q=80&w=1200&auto=format&fit=crop",
    strategyImage: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1200&auto=format&fit=crop",
    outcomeImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "conversion-focused-site",
    title: "Conversion Focused Website",
    client: "B2B Software Provider",
    industry: "SaaS",
    serviceTrack: "Website Development",
    category: "Websites",
    summary:
      "A modular website with campaign-ready pages, SEO foundations, and strong conversion flow from visit to demo request.",
    challenge:
      "Traffic quality was decent but product messaging and page flow were failing to generate enough sales calls.",
    strategy: [
      "Reframed page architecture around buyer intent",
      "Implemented modular sections for fast campaign launches",
      "Improved speed, schema, and technical SEO hygiene",
    ],
    deliverables: ["UX structure", "Responsive frontend", "CMS section library", "SEO setup"],
    outcomes: ["2.1x increase in demo requests", "46% faster page load", "Top ranking gains on key service terms"],
    stack: ["Next.js", "Headless CMS", "Schema", "Performance profiling"],
    duration: "5 weeks",
    year: "2025",
    teamSize: "5 specialists",
    accent: "from-emerald-400 to-teal-500",
    coverImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1400&auto=format&fit=crop",
    challengeImage: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?q=80&w=1200&auto=format&fit=crop",
    strategyImage: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?q=80&w=1200&auto=format&fit=crop",
    outcomeImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "care-mobile-experience",
    title: "Care Mobile Experience",
    client: "Diagnostics Network",
    industry: "Healthcare",
    serviceTrack: "App Development",
    category: "Mobile App",
    summary:
      "A patient app for appointment booking, report tracking, and notifications with a low-friction user journey.",
    challenge:
      "Missed appointments and manual follow-up were impacting customer experience and operations cost.",
    strategy: [
      "Designed end-to-end patient flow from booking to report access",
      "Introduced reminder and status notifications",
      "Built secure account and support escalation pathways",
    ],
    deliverables: ["Mobile UX", "Cross-platform app", "Notification setup", "Release assistance"],
    outcomes: ["37% fewer missed appointments", "58% drop in call-center load", "Strong retention in first 60 days"],
    stack: ["React Native", "Firebase", "REST API", "Event analytics"],
    duration: "8 weeks",
    year: "2025",
    teamSize: "6 specialists",
    accent: "from-indigo-400 to-sky-500",
    coverImage: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1400&auto=format&fit=crop",
    challengeImage: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=1200&auto=format&fit=crop",
    strategyImage: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?q=80&w=1200&auto=format&fit=crop",
    outcomeImage: "https://images.unsplash.com/photo-1580281657521-47fe7d11f5f9?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "business-profile-authority",
    title: "Business Profile Authority Build",
    client: "Professional Legal Firm",
    industry: "Professional Services",
    serviceTrack: "Professional Business Profile",
    category: "Social Presence",
    summary:
      "A trust-first business profile rollout across Facebook, LinkedIn, and Google Business with consistent positioning.",
    challenge:
      "Service pages and social profiles were incomplete, reducing trust for high-value leads.",
    strategy: [
      "Reframed expertise and proof messaging",
      "Unified visual assets and bio systems across channels",
      "Standardized lead capture touchpoints",
    ],
    deliverables: ["Profile optimization", "Visual asset kit", "Messaging framework", "Content guideline"],
    outcomes: ["3.2x profile engagement", "49% increase in direct inquiries", "Improved local search visibility"],
    stack: ["LinkedIn", "Meta Business", "Google Business Profile"],
    duration: "9 days",
    year: "2025",
    teamSize: "3 specialists",
    accent: "from-fuchsia-400 to-pink-500",
    coverImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1400&auto=format&fit=crop",
    challengeImage: "https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=1200&auto=format&fit=crop",
    strategyImage: "https://images.unsplash.com/photo-1552581234-26160f608093?q=80&w=1200&auto=format&fit=crop",
    outcomeImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1200&auto=format&fit=crop",
  },
];

export const portfolioCategories = ["All", ...new Set(portfolioProjects.map((project) => project.category))];
